version: '3'

services:

  dbtitulos:
    image: postgres:9.6
    restart: always
    volumes:
      - dbdatatitulos:/var/lib/postgres
  
  gestiontitulos:
    build: 
      context: .
    depends_on:
      - dbtitulos

volumes:
  dbdatatitulos:



    