version: '3'

services:
  dbtramites:
    image: postgres:9.6
    restart: always
    volumes:
      - dbdatatramites:/var/lib/postgres
    env_file:
      - ../config/gestion-tramites/gestion-tramites-db.env
  gestiontramites:
    build: 
      context: .
    depends_on:
      - dbtramites
    env_file:
      - ../config/gestion-tramites/gestion-tramites.env

volumes:
  dbdatatramites:



    